"""Generate editable Mermaid sources and matching self-contained SVG diagrams.

No external rendering service or API is used. Run from any working directory.
PNG exports are created by capture.mjs using the installed Playwright browser.
"""

from html import escape
from pathlib import Path
import textwrap

OUT = Path(__file__).resolve().parents[1] / "diagrams"
OUT.mkdir(parents=True, exist_ok=True)
COLORS = {
    "core": ("#FFFFFF", "#BFC9BB"),
    "sage": ("#E5EDDF", "#78936B"),
    "teal": ("#E5F0EF", "#739895"),
    "gold": ("#F6ECD2", "#B0985E"),
    "rose": ("#F7E3E1", "#BD8583"),
    "dark": ("#263A2A", "#263A2A"),
}


class Diagram:
    def __init__(self, name, title, subtitle, height, note, sources):
        self.name, self.title, self.subtitle, self.height = (
            name,
            title,
            subtitle,
            height,
        )
        self.note, self.sources, self.nodes, self.edges, self.groups = (
            note,
            sources,
            {},
            [],
            [],
        )

    def node(
        self, id_, title, body, x, y, w=400, h=150, color="core", tag="", kind="card"
    ):
        self.nodes[id_] = dict(
            title=title, body=body, x=x, y=y, w=w, h=h, color=color, tag=tag, kind=kind
        )
        return id_

    def group(self, label, x, y, w, h):
        self.groups.append((label, x, y, w, h))

    def edge(
        self,
        source,
        target,
        label="",
        a="bottom",
        b="top",
        via=(),
        dashed=False,
        label_at=None,
    ):
        self.edges.append((source, target, label, a, b, via, dashed, label_at))

    def anchor(self, id_, side):
        n = self.nodes[id_]
        x, y, w, h = (n[k] for k in ("x", "y", "w", "h"))
        return {
            "top": (x + w / 2, y),
            "bottom": (x + w / 2, y + h),
            "left": (x, y + h / 2),
            "right": (x + w, y + h / 2),
        }[side]

    def render(self):
        svg = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="1480" height="{self.height}" viewBox="0 0 1480 {self.height}" role="img" aria-labelledby="title desc">',
            f'<title id="title">{escape(self.title)}</title><desc id="desc">{escape(self.subtitle + ". " + self.note)}</desc>',
            '<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10 z" fill="#6C8066"/></marker></defs>',
            "<style>text{font-family:Arial,Helvetica,sans-serif;fill:#263A2A}.serif{font-family:Georgia,serif}.caption{fill:#5D7059}.tag{font-size:11px;font-weight:700;letter-spacing:1.6px}</style>",
            f'<rect width="1480" height="{self.height}" fill="#F5F3EB"/>',
            '<rect x="0" y="0" width="1480" height="8" fill="#506C48"/>',
            '<text x="60" y="48" class="tag">MATRIVA / TECHNICAL ATLAS</text>',
            f'<text x="60" y="108" class="serif" font-size="43">{escape(self.title)}</text>',
            f'<text x="60" y="143" font-size="18" class="caption">{escape(self.subtitle)}</text>',
        ]
        for label, x, y, w, h in self.groups:
            svg += [
                f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="none" stroke="#D6DDD0" stroke-width="1.5"/>',
                f'<text x="{x + 20}" y="{y + 29}" class="tag caption">{escape(label)}</text>',
            ]
        for source, target, label, a, b, via, dashed, label_at in self.edges:
            points = [self.anchor(source, a), *via, self.anchor(target, b)]
            coords = " ".join(f"{x},{y}" for x, y in points)
            dash = 'stroke-dasharray="7 6"' if dashed else ""
            svg.append(
                f'<polyline points="{coords}" fill="none" stroke="#6C8066" stroke-width="2" stroke-linejoin="round" {dash} marker-end="url(#arrow)"/>'
            )
            if label:
                lx, ly = label_at or (
                    (points[0][0] + points[-1][0]) / 2,
                    (points[0][1] + points[-1][1]) / 2,
                )
                width = len(label) * 7.4 + 18
                svg += [
                    f'<rect x="{lx - width / 2}" y="{ly - 14}" width="{width}" height="25" rx="4" fill="#F5F3EB"/>',
                    f'<text x="{lx}" y="{ly + 3}" text-anchor="middle" font-size="13" font-weight="600">{escape(label)}</text>',
                ]
        mermaid = [
            "%% Generated by Material/tools/render_diagrams.py; edit the generator to change both formats.",
            "flowchart TB",
        ]
        for id_, n in self.nodes.items():
            x, y, w, h = (n[k] for k in ("x", "y", "w", "h"))
            fill, stroke = COLORS[n["color"]]
            dark = n["color"] == "dark"
            if n["kind"] == "decision":
                svg.append(
                    f'<polygon points="{x + w / 2},{y} {x + w},{y + h / 2} {x + w / 2},{y + h} {x},{y + h / 2}" fill="{fill}" stroke="{stroke}" stroke-width="1.5"/>'
                )
                svg.append(
                    f'<text x="{x + w / 2}" y="{y + h / 2 - 5}" text-anchor="middle" font-size="22" font-weight="700">{escape(n["title"])}</text>'
                )
                for i, line in enumerate(n["body"]):
                    svg.append(
                        f'<text x="{x + w / 2}" y="{y + h / 2 + 22 + i * 21}" text-anchor="middle" font-size="15">{escape(line)}</text>'
                    )
            else:
                svg.append(
                    f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{h / 2 if n["kind"] == "end" else 10}" fill="{fill}" stroke="{stroke}" stroke-width="1.5"/>'
                )
                color = ' style="fill:#F5F3EB"' if dark else ""
                titles = textwrap.wrap(n["title"], max(15, int((w - 44) / 12)))
                svg.append(
                    f'<text x="{x + 22}" y="{y + 25}" class="tag"{color}>{escape(n["tag"])}</text>'
                )
                for i, title in enumerate(titles):
                    svg.append(
                        f'<text x="{x + 22}" y="{y + 55 + i * 25}" font-size="23" font-weight="700"{color}>{escape(title)}</text>'
                    )
                lines = [
                    line
                    for body in n["body"]
                    for line in textwrap.wrap(body, max(20, int((w - 44) / 8.3)))
                ]
                for i, line in enumerate(lines):
                    svg.append(
                        f'<text x="{x + 22}" y="{y + 82 + (len(titles) - 1) * 25 + i * 22}" font-size="17"{color}>{escape(line)}</text>'
                    )
                assert (
                    82 + (len(titles) - 1) * 25 + max(0, len(lines) - 1) * 22 < h - 6
                ), (self.name, id_, "text needs a taller card")
            label = "<br/>".join(
                escape(part).replace('"', "&quot;") for part in [n["title"], *n["body"]]
            )
            shape = (
                f'{id_}{{"{label}"}}'
                if n["kind"] == "decision"
                else f'{id_}["{label}"]'
            )
            mermaid.append("    " + shape)
            mermaid.append(
                f"    style {id_} fill:{fill},stroke:{stroke},color:{'#F5F3EB' if dark else '#263A2A'}"
            )
        for source, target, label, _a, _b, _via, dashed, _label_at in self.edges:
            connector = "-.->" if dashed else "-->"
            mermaid.append(
                f"    {source} {connector}"
                + (f'|"{label}"|' if label else "")
                + f" {target}"
            )
        svg += [
            f'<line x1="60" x2="1420" y1="{self.height - 94}" y2="{self.height - 94}" stroke="#CCD4C6"/>',
            f'<text x="60" y="{self.height - 64}" font-size="16" class="caption">{escape(self.note)}</text>',
            f'<text x="60" y="{self.height - 34}" font-size="13" class="caption">Code reference: {escape(self.sources)}</text>',
            f'<text x="1420" y="{self.height - 34}" text-anchor="end" class="tag">{self.name.upper()}</text></svg>',
        ]
        (OUT / f"{self.name}.svg").write_text("\n".join(svg) + "\n")
        (OUT / f"{self.name}.mmd").write_text("\n".join(mermaid) + "\n")


def architecture():
    d = Diagram(
        "architecture",
        "A modular monolith, with clear boundaries",
        "One browser workspace. One API. Safety and care decisions stay on the server.",
        1120,
        "Solid arrows: application data flow. Dashed arrows: optional external adapters. Development uses SQLite; production uses PostgreSQL.",
        "frontend/app · backend/app/main.py · services/chat.py · rag/local/ · docker-compose.prod.yml",
    )
    d.node(
        "browser",
        "Next.js + React workspace",
        [
            "Chat, care cards, settings · JSON / SSE",
            "Patient and role-gated staff views",
        ],
        70,
        210,
        400,
        150,
        "sage",
        "CLIENT / TYPESCRIPT",
    )
    d.node(
        "api",
        "FastAPI request boundary",
        ["Validation, JWT / roles, CORS", "Quotas, request IDs, metrics"],
        530,
        210,
        400,
        150,
        "dark",
        "API / PYTHON",
    )
    d.node(
        "providers",
        "Optional provider adapters",
        ["Groq generation · Gemini embeddings", "Tavily search if configured"],
        990,
        210,
        400,
        150,
        "gold",
        "EXTERNAL MODE ONLY",
    )
    d.group("BACKEND MODULES / ONE DEPLOYABLE SERVICE", 50, 420, 1360, 275)
    d.node(
        "safety",
        "Safety + guard rails",
        ["Classify input, use consented context", "Validate output and citations"],
        70,
        480,
        400,
        165,
        "rose",
        "POLICY / FAIL CLOSED",
    )
    d.node(
        "rag",
        "Evidence + retrieval",
        ["Local hybrid index / extraction", "External LangChain pipeline"],
        530,
        480,
        400,
        165,
        "sage",
        "TWO ENGINE MODES",
    )
    d.node(
        "care",
        "Deterministic care services",
        ["Dating, plans, readings, meals", "Check-ins, screening, summary"],
        990,
        480,
        400,
        165,
        "teal",
        "YAML / JSON RULES",
    )
    d.node(
        "files",
        "Versioned reference files",
        ["Rules, nutrient data, book structure", "Reviewed independently of software"],
        70,
        820,
        400,
        155,
        "core",
        "FILES / SOURCE CONTROL",
    )
    d.node(
        "db",
        "SQLAlchemy data layer",
        ["Accounts, consent, care, messages", "Approved documents and chunks"],
        530,
        820,
        400,
        155,
        "core",
        "SQLITE / POSTGRESQL + PGVECTOR",
    )
    d.node(
        "redis",
        "Redis shared quotas",
        ["Atomic counters across workers", "Production fails closed on outage"],
        990,
        820,
        400,
        155,
        "core",
        "REQUIRED IN PRODUCTION",
    )
    d.edge("browser", "api", a="right", b="left")
    d.edge("api", "safety", via=[(730, 390), (270, 390)])
    d.edge("api", "rag")
    d.edge("api", "care", via=[(730, 390), (1190, 390)])
    d.edge(
        "rag",
        "providers",
        a="right",
        b="bottom",
        via=[(960, 565), (960, 380), (1190, 380)],
        dashed=True,
    )
    d.edge("safety", "files")
    d.edge("rag", "db", "approved evidence", label_at=(730, 744))
    d.edge("care", "db", via=[(1190, 730), (730, 730)])
    d.edge("care", "files", via=[(1190, 780), (270, 780)])
    d.edge(
        "api",
        "redis",
        a="right",
        b="right",
        via=[(950, 285), (950, 395), (1440, 395), (1440, 897)],
    )
    return d


def working():
    d = Diagram(
        "working-flow",
        "How a chat answer is made",
        "The live request path — blocking and streaming endpoints share the same safety contract.",
        1980,
        "Fixed safety replies also persist. A validated final SSE event can replace earlier deltas; the client must apply the correction.",
        "services/chat.py · rag/pipeline.py · rag/local/engine.py · safety/guardrails/output.py",
    )
    d.node(
        "question",
        "Receive the question",
        ["POST /chat or /chat/stream"],
        540,
        190,
        400,
        115,
        "dark",
        "01 / REQUEST",
    )
    d.node(
        "safety",
        "Safety + personal guard rails",
        [
            "Intent, danger signs, risky requests",
            "Classifier failure: service unavailable",
        ],
        540,
        365,
        400,
        150,
        "rose",
        "02 / BEFORE RETRIEVAL",
    )
    d.node(
        "refuse",
        "Refuse risky advice",
        ["Fixed, specific explanation", "No retrieval or provider call"],
        70,
        365,
        380,
        150,
        "rose",
        "STOP / HIGH RISK",
    )
    d.node(
        "urgent",
        "Escalate urgent symptoms",
        ["Emergency message and helplines", "No retrieval or provider call"],
        1030,
        365,
        380,
        150,
        "rose",
        "STOP / URGENT",
    )
    d.node(
        "context",
        "Prepare a safe turn",
        ["Resolve follow-ups and language", "Use consented profile context"],
        540,
        590,
        400,
        150,
        "core",
        "03 / CONTEXT",
    )
    d.node(
        "action",
        "Record a safe statement",
        ["Consented meal / reading log", "Return the action summary"],
        70,
        590,
        380,
        150,
        "teal",
        "ACTION / WHEN DETECTED",
    )
    d.node(
        "local",
        "Offline hybrid retrieval",
        [
            "BM25, n-grams, concepts, LSA, graph",
            "Feedback, fusion, rerank and diversity",
        ],
        70,
        835,
        610,
        160,
        "sage",
        "04A / RAG_ENGINE=LOCAL",
    )
    d.node(
        "external",
        "External hybrid retrieval",
        [
            "Keyword / vector retrieval and rerank",
            "Gemini embeddings; optional Tavily web sources",
        ],
        800,
        835,
        610,
        160,
        "gold",
        "04B / RAG_ENGINE=EXTERNAL",
    )
    d.node(
        "gate",
        "Evidence sufficient?",
        ["Approved evidence / external labels"],
        540,
        1080,
        400,
        120,
        "gold",
        kind="decision",
    )
    d.node(
        "abstain",
        "Say evidence is insufficient",
        ["Fixed response; no invented claims"],
        70,
        1070,
        380,
        135,
        "gold",
        "STOP / NO SUPPORT",
    )
    d.node(
        "extract",
        "Extract from the passages",
        ["Local composer builds a cited answer", "No external model or API key"],
        70,
        1280,
        610,
        145,
        "sage",
        "05A / OFFLINE COMPOSITION",
    )
    d.node(
        "generate",
        "Generate from the context packet",
        [
            "LangChain → ChatGroq → citation validation",
            "Grounded fallback when a provider fails",
        ],
        800,
        1280,
        610,
        145,
        "gold",
        "05B / EXTERNAL GENERATION",
    )
    d.node(
        "validate",
        "Check output + citations",
        [
            "Reject unsafe advice or invalid sources",
            "Replace the answer when checks fail",
        ],
        540,
        1510,
        400,
        150,
        "rose",
        "06 / FINALIZE",
    )
    d.node(
        "final",
        "Persist and return",
        [
            "Answer, sources, notices, suggestions",
            "JSON response or validated final SSE",
        ],
        540,
        1710,
        400,
        125,
        "sage",
        "07 / DELIVERY",
    )
    d.edge("question", "safety")
    d.edge("safety", "refuse", "block", a="left", b="right")
    d.edge("safety", "urgent", "urgent", a="right", b="left")
    d.edge("safety", "context", "safe / caution")
    d.edge("context", "action", "statement", a="left", b="right", label_at=(495, 567))
    d.edge(
        "context",
        "local",
        via=[(740, 790), (375, 790)],
        label="local",
        label_at=(375, 800),
    )
    d.edge(
        "context",
        "external",
        via=[(740, 790), (1105, 790)],
        label="external",
        label_at=(1105, 800),
    )
    d.edge("local", "gate", via=[(375, 1030), (740, 1030)])
    d.edge("external", "gate", via=[(1105, 1030), (740, 1030)])
    d.edge("gate", "abstain", "no", a="left", b="right")
    d.edge(
        "gate",
        "extract",
        "yes / local",
        via=[(740, 1240), (375, 1240)],
        label_at=(375, 1250),
    )
    d.edge(
        "gate",
        "generate",
        "yes / external",
        via=[(740, 1240), (1105, 1240)],
        label_at=(1105, 1250),
    )
    d.edge("extract", "validate", via=[(375, 1460), (740, 1460)])
    d.edge("generate", "validate", via=[(1105, 1460), (740, 1460)])
    d.edge("validate", "final")
    d.edge(
        "action",
        "final",
        a="bottom",
        b="left",
        via=[(260, 770), (40, 770), (40, 1772)],
        dashed=True,
    )
    return d


def journey():
    d = Diagram(
        "user-flow",
        "One workspace, three everyday journeys",
        "The patient journey from first visit to asking, tracking and controlling personal data.",
        1190,
        "Inline cards live inside /chat. Staff document review, evaluations and feedback use separate role-gated views.",
        "frontend/app/{signup,onboarding,chat,settings} · chat/page.tsx QUICK_ACTIONS · components/care/",
    )
    d.node(
        "arrive",
        "Discover MATRIVA",
        ["Read the scope and limits", "Open signup or login"],
        60,
        230,
        300,
        155,
        "sage",
        "01 / LANDING",
    )
    d.node(
        "account",
        "Create an account",
        ["Name, email, password", "Or sign into an existing account"],
        410,
        230,
        300,
        155,
        "core",
        "02 / AUTHENTICATION",
    )
    d.node(
        "setup",
        "Set up with consent",
        ["Week / last period / due date", "Region, diet and storage consent"],
        760,
        230,
        300,
        155,
        "core",
        "03 / ONBOARDING",
    )
    d.node(
        "workspace",
        "Enter the workspace",
        ["Chat + sidebar shortcuts", "One place for care tools"],
        1110,
        230,
        310,
        155,
        "dark",
        "04 / CHAT",
    )
    d.node(
        "pause",
        "Pause setup",
        ["No consented health profile saved", "Return when ready to continue"],
        760,
        485,
        300,
        155,
        "gold",
        "CONSENT NOT GRANTED",
    )
    d.node(
        "ask",
        "Ask and learn",
        [
            "Question → safety → evidence",
            "Sources, refusal or escalation",
            "Book, library and knowledge map",
        ],
        60,
        745,
        400,
        190,
        "sage",
        "JOURNEY A / GUIDANCE",
    )
    d.node(
        "track",
        "Plan and track",
        [
            "Plan, check-in, screening",
            "Readings, meals, food guide",
            "Printable doctor summary",
        ],
        540,
        745,
        400,
        190,
        "teal",
        "JOURNEY B / CARE",
    )
    d.node(
        "privacy",
        "Manage your data",
        [
            "Settings and safety profile",
            "Download the JSON export",
            "Withdraw consent / delete account",
        ],
        1020,
        745,
        400,
        190,
        "core",
        "JOURNEY C / CONTROL",
    )
    d.edge("arrive", "account", a="right", b="left")
    d.edge("account", "setup", a="right", b="left")
    d.edge("setup", "workspace", a="right", b="left")
    d.edge("setup", "pause", "leave setup", dashed=True, label_at=(910, 456))
    d.edge("workspace", "ask", via=[(1265, 680), (260, 680)])
    d.edge("workspace", "track", via=[(1265, 680), (740, 680)])
    d.edge("workspace", "privacy", via=[(1265, 680), (1220, 680)])
    return d


def review():
    d = Diagram(
        "source-review",
        "Evidence earns its place in the answer",
        "Uploading or indexing a document never counts as clinical approval.",
        1010,
        "Only active documents with approved documents and sources enter ordinary retrieval. An admin action is not clinical certification.",
        "api/admin.py · services/knowledge.py · rag/local/corpus.py · repositories/knowledge.py",
    )
    labels = [
        (
            "upload",
            "Upload + metadata",
            ["PDF or text-based file", "Source, domain, evidence label"],
            "01 / ADMIN",
        ),
        (
            "extract",
            "Extract the content",
            ["Text extraction / OCR", "Validate supported formats"],
            "02 / PROCESS",
        ),
        (
            "chunks",
            "Store passages",
            ["Chunks with source provenance", "Pending document and source"],
            "03 / PENDING",
        ),
        (
            "index",
            "Index successfully",
            ["Reindex before approval", "Failed indexing blocks approval"],
            "04 / INDEX STATUS",
        ),
    ]
    for i, (id_, title, body, tag) in enumerate(labels):
        d.node(id_, title, body, 60 + i * 350, 240, 310, 170, "core", tag)
    d.node(
        "human",
        "Review the actual source",
        ["Compare extracted text to source", "Check provenance and suitability"],
        1110,
        535,
        310,
        170,
        "gold",
        "05 / HUMAN DECISION",
    )
    d.node(
        "approve",
        "Approve for retrieval",
        ["Document + source approved", "Document active; record reviewer"],
        760,
        535,
        310,
        170,
        "sage",
        "06 / ELIGIBILITY",
    )
    d.node(
        "retrieve",
        "Retrieve + cite",
        ["Approved passages only", "Evidence gate still applies"],
        410,
        535,
        310,
        170,
        "sage",
        "07 / ANSWER PATH",
    )
    d.node(
        "reject",
        "Reject or archive",
        ["Kept outside ordinary retrieval", "Pending remains ineligible"],
        60,
        535,
        310,
        170,
        "rose",
        "ALTERNATE / EXCLUDE",
    )
    d.edge("upload", "extract", a="right", b="left")
    d.edge("extract", "chunks", a="right", b="left")
    d.edge("chunks", "index", a="right", b="left")
    d.edge("index", "human", "indexed")
    d.edge("human", "approve", a="left", b="right")
    d.edge("approve", "retrieve", a="left", b="right")
    d.edge(
        "human",
        "reject",
        "reject / archive",
        a="bottom",
        b="bottom",
        via=[(1265, 790), (215, 790)],
        label_at=(740, 790),
    )
    return d


def deployment():
    d = Diagram(
        "deployment",
        "The production stack and its boundaries",
        "Docker Compose currently defines four services. Public ingress remains an operator responsibility.",
        1160,
        "The production Compose file exposes internal ports only. A reverse proxy / published ports and HTTPS must be configured for public access.",
        "docker-compose.prod.yml · backend/Dockerfile · frontend/Dockerfile · backend/docker-entrypoint.sh",
    )
    d.node(
        "device",
        "Browser / device",
        ["UI + API request origins", "Browser-visible API URL at build time"],
        70,
        210,
        400,
        150,
        "sage",
        "CLIENT",
    )
    d.node(
        "ingress",
        "Operator-managed ingress",
        ["HTTPS / reverse proxy", "Not supplied by production Compose"],
        540,
        210,
        400,
        150,
        "gold",
        "PUBLIC BOUNDARY",
    )
    d.group("DOCKER COMPOSE / PRIVATE SERVICE NETWORK", 50, 425, 1370, 570)
    d.node(
        "web",
        "Next.js standalone",
        ["Node 24, public assets included", "No backend credentials in container"],
        80,
        490,
        380,
        170,
        "sage",
        "FRONTEND / 3000",
    )
    d.node(
        "backend",
        "FastAPI service",
        ["Python 3.11, non-root runtime", "Alembic migrations on startup"],
        550,
        490,
        380,
        170,
        "dark",
        "BACKEND / 8000",
    )
    d.node(
        "runtime",
        "Writable runtime volume",
        ["Evaluation reports", "Owned by the backend user"],
        1040,
        490,
        350,
        170,
        "core",
        "BACKEND_RUNTIME",
    )
    d.node(
        "postgres",
        "PostgreSQL + pgvector",
        ["Accounts, care and conversation data", "Documents / vector index; db_data"],
        250,
        790,
        420,
        155,
        "core",
        "DATABASE / PG16",
    )
    d.node(
        "redis",
        "Authenticated Redis",
        ["Shared quotas; authenticated health", "Persistent redis_data volume"],
        810,
        790,
        420,
        155,
        "core",
        "REDIS / 7",
    )
    d.edge("device", "ingress", a="right", b="left")
    d.edge("ingress", "web", via=[(740, 390), (270, 390)])
    d.edge("ingress", "backend")
    d.edge("backend", "runtime", a="right", b="left")
    d.edge("backend", "postgres", via=[(740, 730), (460, 730)])
    d.edge("backend", "redis", via=[(740, 730), (1020, 730)])
    return d


def privacy():
    d = Diagram(
        "privacy-flow",
        "Consent, export and deletion are distinct",
        "Account authentication is separate from permission to store a health profile.",
        1220,
        "Profile deletion / consent withdrawal retains chat history. Account deletion removes the account and associated personal records.",
        "api/privacy.py · api/profile.py · services/profile.py · services/care/privacy.py · models/entities.py",
    )
    d.node(
        "user",
        "Signed-in account",
        ["JWT resolves the account owner", "Each endpoint authorizes ownership"],
        540,
        210,
        400,
        150,
        "dark",
        "IDENTITY",
    )
    d.node(
        "consent",
        "Health-storage consent?",
        ["Required for health / care writes"],
        540,
        430,
        400,
        120,
        "gold",
        kind="decision",
    )
    d.node(
        "deny",
        "Declined / withdrawn",
        ["No health profile storage", "Withdrawal purges profile + care"],
        70,
        430,
        380,
        155,
        "rose",
        "NO CONSENT",
    )
    d.node(
        "store",
        "Store profile + care",
        ["Pregnancy, safety profile, readings", "Meals, check-ins and care records"],
        1030,
        430,
        380,
        155,
        "teal",
        "CONSENTED WRITES",
    )
    d.node(
        "export",
        "Export my data",
        ["GET /privacy/export", "Account, profile, care and messages"],
        70,
        770,
        400,
        175,
        "sage",
        "CONTROL A / JSON DOWNLOAD",
    )
    d.node(
        "profiledelete",
        "Delete the health profile",
        ["DELETE /profile or withdraw consent", "Profile + care erased; chats remain"],
        540,
        770,
        400,
        175,
        "gold",
        "CONTROL B / LIMITED SCOPE",
    )
    d.node(
        "accountdelete",
        "Delete my account",
        [
            "DELETE /privacy/account",
            "Associated personal records removed",
            "Old token no longer resolves a user",
        ],
        1030,
        770,
        380,
        190,
        "rose",
        "CONTROL C / ACCOUNT SCOPE",
    )
    d.edge("user", "consent")
    d.edge("consent", "deny", "no", a="left", b="right")
    d.edge("consent", "store", "yes", a="right", b="left")
    d.edge("user", "export", a="left", via=[(490, 285), (490, 695), (270, 695)])
    d.edge("user", "profiledelete", a="left", via=[(490, 285), (490, 695), (740, 695)])
    d.edge(
        "user", "accountdelete", a="right", via=[(990, 285), (990, 695), (1220, 695)]
    )
    return d


for diagram in (
    architecture(),
    working(),
    journey(),
    review(),
    deployment(),
    privacy(),
):
    diagram.render()
    print(f"Rendered {diagram.name}.svg + .mmd")
